apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 1
    version: 2.6.0
    config:
      log.message.format.version: 2.6
      num.partitions: 1
      offsets.topic.replication.factor: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
        log4j.logger.kafka.authorizer.logger: INFO
        log4j.logger.kafka.controller: INFO
        log4j.logger.kafka.log.LogCleaner: INFO
    jvmOptions:
      gcLoggingEnabled: false
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    template:
      pod:
        terminationGracePeriodSeconds: 120
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
    logging:
      type: inline
      loggers:
        rootLogger.level: INFO
        zookeeper.root.logger: INFO
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
    jvmOptions:
      gcLoggingEnabled: false
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
