apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    config:
      log.message.format.version: 2.5
      log.retention.minutes: 720
      # single node setup
      num.partitions: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    logging:
      type: inline
      loggers:
        log4j.logger.kafka: INFO
        log4j.logger.kafka.authorizer.logger: INFO
        log4j.logger.kafka.controller: INFO
        log4j.logger.kafka.log.LogCleaner: INFO
        log4j.logger.kafka.network.Processor: INFO
        log4j.logger.kafka.network.RequestChannel$: INFO
        log4j.logger.kafka.request.logger: INFO
        log4j.logger.kafka.server.KafkaApis: INFO
        log4j.logger.org.I0Itec.zkclient.ZkClient: INFO
        log4j.logger.org.apache.kafka: INFO
        log4j.logger.org.apache.zookeeper: INFO
        log4j.logger.state.change.logger: INFO
    resources:
      requests:
        cpu: "1000m"
        memory: "2Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    tlsSidecar:
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
    jvmOptions:
      gcLoggingEnabled: false
    listeners:
      plain: {}
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    template:
      pod:
        terminationGracePeriodSeconds: 120
    storage:
      type: persistent-claim
      size: "1Gi"
  zookeeper:
    replicas: 1
    logging:
      type: inline
      loggers:
        rootLogger.level: INFO
        zookeeper.root.logger: INFO
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    tlsSidecar:
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
    jvmOptions:
      gcLoggingEnabled: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: "1Gi"
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: "250m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
    userOperator:
      resources:
        limits:
          cpu: "250m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
    tlsSidecar:
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
