apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemis
metadata:
  name: my-broker
spec:
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    size: 1
    image: registry.redhat.io/amq7/amq-broker:7.7
    requireLogin: true
    persistenceEnabled: true
    messageMigration: false
    journalType: nio
  console:
    expose: true
  acceptors:
    - name: all
      protocols: all
      port: 61612
      sslEnabled: false
      connectionsAllowed: 10
      expose: true
