apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: mysql-source
  labels:
    strimzi.io/cluster: my-connect
spec:
  tasksMax: 1
  class: io.debezium.connector.mysql.MySqlConnector
  config:
    database.server.id: "224466"
    database.server.name: "my-mysql"
    database.dbname: "cdcdb"
    database.hostname: "my-mysql-svc"
    database.port: 3306
    database.user: "${file:/opt/kafka/external-configuration/connectors/config.properties:mysql.username}"
    database.password: "${file:/opt/kafka/external-configuration/connectors/config.properties:mysql.password}"
    database.include.list: "cdcdb"
    table.include.list: "cdcdb.customers"
    database.allowPublicKeyRetrieval: true
    database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "cdcdb.dbhistory"
